### ISSUE TITLE
Access control rules from ingress annotations

### ISSUE THREAD

**Issue by laurivosandi** [authelia/chartrepo#128]
I think there is disconnect between Authelia configuration and Ingress CRD-s and Authelia should support access control rules in Ingress CRD annotations, so something like following:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: foo
  namespace: foo
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: default
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: authelia-chain-foo-authelia-auth@kubernetescrd
    traefik.ingress.kubernetes.io/router.tls: "true"
    external-dns.alpha.kubernetes.io/target: traefik.example.com
    authelia.com/acl-policy: two_factor
    authelia.com/acl-networks: 1.2.3.4
    authelia.com/acl-subject: "group:admins"
spec:
  rules:
  - host: foo.example.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: foo
            port:
              number: 8000
  tls:
  - hosts:
    - foo.example.com
    secretName: foo-tls
```

Maybe it's also possible to annotate paths and get even more fine grained control
