### ISSUE TITLE
Current chart version is broken since 4.37 upgrade

### ISSUE THREAD

**Issue by romancin** [authelia/chartrepo#186]
Today, flux updated my authelia release and left the pod in CrashLoopBackOff. Looking at the logs:
```
ime="2022-10-23T09:07:33+02:00" level=error msg="Configuration: authentication_backend: file: password: argon2: option 'memory' is configured as '65536' but must be greater than or equal to '524288' or '65536' (the value of 'parallelism) multiplied by '8'"
time="2022-10-23T09:07:33+02:00" level=fatal msg="Can't continue due to the errors loading the configuration"
```

Looking at the ConfigMap, the parallelism value is not correct:
```
algorithm: 'argon2'\n      argon2:\n        variant: 'argon2id'\n        iterations:
    3\n        memory: 65536\n        parallelism: 65536\n        key_length: 32\n
    \       salt_length: 16\n      
```
Maybe problem is on this line:

https://github.com/authelia/chartrepo/blob/078613049f048cb980e36177b1eac938eeb89e84/charts/authelia/templates/configMap.yaml#L139

You are looking for parallelism value in the password block ($auth.file.password.parallelism) instead of looking for it inside argon2 block ($auth.file.password.argon2.parallelism)? As $auth.file.password.parallelism value doesn't exist in my case (as I changed the configuration to the current one in values.yaml, it is taking the same value as the memory, which lefts the application broken.

Here is the configuration block:
```
authentication_backend:
        password_reset:
          disable: false
        file:
          enabled: true
          path: /config/users_database.yml
          watch: true
          search:
            email: false
            case_insensitive: false
          password:
            algorithm: argon2
            argon2:
              variant: argon2id
              iterations: 3
              memory: 65536
              parallelism: 4
              key_length: 32
              salt_length: 16
```

Thank you!
