### ISSUE TITLE
configMap.identity_providers.oidc.clients[n].secret has to be exposed via plain text which is a security concern

### ISSUE THREAD

**Issue by atropos112** [authelia/chartrepo#199]
Currently if i want to add oidc clients while using the chart I can simply add something like

```
configMap:
  identity_providers:
      oidc:
        clients:                                                                                                                                                                                                                                                                 
        - id: gitlab                                                                                                                                                                                                                                                           
          description: gitlab                                                                                                                                                                                                                                                  
          secret: complicatedSecretgoeshere
```
and this simplifies my usage of authelia significantly and is nice and readable (thank you!). What concerns me is those secrets are out in the open in my values file, and there is currently no way for me to use the helm chart and point to k8s secrets instead.
