### ISSUE TITLE
Beta Testers Unite: Information About the Repo

### ISSUE THREAD

**Issue by james-d-elliott** [authelia/chartrepo#2]
This thread is mainly intended as a place for me to move the TODO list, but also for people to suggest things for when the chart is "officially" released. It is also fine if you want to open individual issues and this is more encouraged so we can link commit history to individual issues.

It's also a place you're free to just ask questions. 

# Basic Overview

The chart is currently in beta and is subject to breaking changes in any chart release until the 1.0.0 release as per semver rules. Once we hit 1.0.0 breaking changes are intended to be limited to major version bumps (1.x.x -> 2.x.x.x). Feature bumps will be restricted to the minor version number (1.0.x -> 1.1.x), and everything else is a patch release which just fixes bugs.

Currently the main thing I'm in thought over is the config map, specifically the providers. There are essentially two ways I can configure them. I can make it so if they're defined they are enabled, or I can make individual switches. For example I can add a key to mysql called "enabled" which is a boolean, which is false by default. The advantage of the enabled option for these purposes is that all options are configured in values, the disadvantage is the chart will require a considerable amount of additional curly braces. I am currently leaning towards using the enabled switch, but if anyone has arguments against it then please let me know.

# To Do List

- [ ] Setup CI
  - [ ] Chart Linting (chart-testing)
  - [ ] Chart Releaser
  - [ ] yamllint config
  - [ ] Merge restrictions (version bump requirement)
  - [ ] Unit Testing (terratest?)
  - [ ] Integration Testing (kind)
- [ ] Chart Values Validation
  - [ ] Enabled/Defined Providers
  - [ ] Statefulness (probably needs tweaking)
- [ ] Documentation
  - [ ] Chart Documentation
  - [ ] Automatically Generate Website Layout with versioned docs (jekyll)

**Comment by crutonjohn** [comment]
i believe that the "enabled/disabled" or "true/false" pattern is the one i've seen mostly everywhere.

are you running this in your cluster yet, @james-d-elliott ?

**Comment by james-d-elliott** [comment]
> 
> 
> i believe that the "enabled/disabled" or "true/false" pattern is the one i've seen mostly everywhere.
> 
> are you running this in your cluster yet, @james-d-elliott ?

Yes I'm using it in my cluster as a DaemonSet with Postgres, Redis Sentinel, and LDAP. There have been no major issues.

The enabled/disabled method is what I went with, as I use argocd and you have to manually specify values that are commented out instead of overriding them.

**Comment by james-d-elliott** [comment]
@danielskowronski

**Comment by danielskowronski** [comment]
> We would more than welcome examples in the form of values-<description>.yaml.

The problem for me is that I couldn't contribute any example values of reasonable quality without fully reverse engineering this chart. It is my basic expectation of Helm chart that at least it can be deployed based on samples and then tweaked on top of that. I'm aware that this is still work in progress, but on that stage I can't reasonably offer much help as I'm not even sure if I use it correctly.

> Please provide specifics, alternatively we'd welcome correction contributions for this.

This was deliberately general statement as it represents my reception of provided documentation. But most trouble I got from trying to set values for sensitive data (secrets). 

> Please provide specifics. Vague information like this is very unhelpful.

I refer to all warnings in Authelia documentation that suggest future changes to behaviou combined with whole `BREAKING.md`. Again, as a whole experience and not something I could do quick PR for.

With regards to accessibility, I also want to emphasize that I believe in 2025 it's harder to get community and contributors for software that is perfectly capable of natively running on k8s without Helm chart. I'm using Authelia for years on bare-metal and I know it's not the only use-case for it, but it's quite important part of landscape today. That's why I believe Helm chart should be easy to adopt for basic installation by average user without digging into template source code.

**Comment by willmurnane** [comment]
I'm currently trying to get the helm chart deployed, and have struggled a bit getting it wired up. I think the chart should be slightly more opinionated to make it easier to use. For example, I initially didn't realize that "the postgres password should come from a `Secret`" doesn't imply "the secret will be mounted into the pod", and I think it'd be relatively easy to make that happen. The current system which just fails the release if you don't explicitly spell out the secret mount (in non-standard syntax) is painful.

For future reference, here's what I've got configured so far:
```
apiVersion: v1
kind: Namespace
metadata:
  name: authelia
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authelia
  namespace: authelia
spec:
  bootstrap:
    initdb:
      database: authelia
      owner: authelia
  resources:
    requests:
      memory: 128Mi
      cpu: 500m
  postgresql:
  storage:
    size: 10Gi
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: authelia
  namespace: flux-system
spec:
  interval: 24h
  timeout: 60s
  url: https://charts.authelia.com
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authelia
  namespace: flux-system
spec:
  interval: 10m
  timeout: 10m
  chart:
    spec:
      chart: "authelia"
      version: 0.11.5
      sourceRef:
        kind: HelmRepository
        name: authelia
      interval: 5m
  releaseName: authelia
  targetNamespace: authelia
  values:
    rbac:
      enabled: true
    ingress:
      enabled: true
      gatewayAPI:
        enabled: true
        parentRefs:
          - name: cilium-gateway
            namespace: gateway
    configMap:
      authentication_backend:
        file:
          enabled: true
      notifier:
        filesystem:
          enabled: true
      session:
        cookies:
          - domain: 'will.murnane.family'
            subdomain: authelia
            name: 'authelia_session'
            same_site: 'lax'
            inactivity: '30m'
            expiration: '1d'
      storage:
        postgres:
          enabled: true
          address: tcp://authelia-rw.authelia:5432/authelia
          password:
            secret_name: authelia-app
    pod:
      kind: Deployment
    secret:
      additionalSecrets:
        authelia-app:
          items:
            - key: password
              path: storage.postgres.password.txt
```
This is enough to deploy and start Authelia (and make it accessible at `https://authelia.will.murnane.family`) on the current chart. To log in, I shelled into the pod and edited `/config/user_database.yml` to set `disabled: false` and restarted the pod.
