### ISSUE TITLE
Cannot set Mysql or Postgres storage without TLS

### ISSUE THREAD

**Issue by davidcampos** [authelia/chartrepo#239]
With 0.9.0-beta3, cannot set Mysql or Postgres storage without TLS.

Using the following storage configuration:
```yaml
storage:
  local:
    enabled: false
  mysql:
    enabled: true
    address: 'tcp://mariadb:3306'
    database: authelia
    username: root
    timeout: '10s'
    tls:
      enabled: false
```

Getting the following error:
`level=error msg="Error occurred running a startup check" error="error pinging database: TLS requested but server does not support TLS" provider=storage`

**Comment by wustus** [comment]
Me too. As far as I can see, the check if TLS is enabled is missing here.

```
mysql:
  address: {{ $storage.mysql.address | squote }}
  timeout: {{ include "authelia.func.dquote" ($storage.mysql.timeout | default "5 seconds") }}
  database: {{ $storage.mysql.database | default "authelia" | squote }}
  username: {{ $storage.mysql.username |  default "authelia" | squote }}
  tls:
    server_name: {{ $storage.mysql.tls.server_name | default "" | squote }}
    skip_verify: {{ $storage.mysql.tls.skip_verify | default false }}
    minimum_version: {{ $storage.mysql.tls.minimum_version | default "TLS1.2" | squote }}
    maximum_version: {{ $storage.mysql.tls.maximum_version | default "TLS1.3" | squote }}
```

compared to session

```
redis:
  host: {{ $session.redis.host | squote }}
  port: {{ $session.redis.port | default 6379 }}
  {{- if $session.redis.username }}
  username: {{ $session.redis.username | squote }}
  {{- end }}
  database_index: {{ $session.redis.database_index | default 0 }}
  maximum_active_connections: {{ $session.redis.maximum_active_connections | default 8 }}
  minimum_idle_connections: {{ $session.redis.minimum_idle_connections | default 0 }}
  {{- if $session.redis.tls.enabled }}
  tls:
    server_name: {{ $session.redis.tls.server_name | default "" | squote }}
    skip_verify: {{ $session.redis.tls.skip_verify | default false }}
    minimum_version: {{ $session.redis.tls.minimum_version | default "TLS1.2" | squote }}
    maximum_version: {{ $session.redis.tls.maximum_version | default "TLS1.3" | squote }}
  {{- end }}
```

I'll create a PR.
