### ISSUE TITLE
Cannot set configMap.session.cookies using ConfigMap generator

### ISSUE THREAD

**Issue by CyberHippo** [authelia/chartrepo#245]
The section `configMap.session.cookies` is not templated properly because the variable `$cookies` is not set in the ConfigMap template : setting a cookie does not create the related entry in the configmap.

Example values:
```yaml
configMap:
  session:
    cookies:
      - name: 'authelia_session'
        domain: "example.com"
[redacted]
```
which produces the following ConfigMap:
```yaml
---
# Source: authelia/charts/authelia/templates/configMap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia
  labels: 
    app.kubernetes.io/name: authelia
    app.kubernetes.io/instance: authelia
    app.kubernetes.io/version: 4.37.5
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: authelia-0.8.58
data:
  configuration.yaml: |
    [redacted]
    session:
      name: 'authelia_session'
      domain: 'example.com'
      same_site: 'lax'
      expiration: 1h
      inactivity: 5m
      remember_me_duration: 1M
```
