### ISSUE TITLE
Indentation issue in traefikCRD/middlewares.yaml

### ISSUE THREAD

**Issue by stocc** [authelia/chartrepo#250]
Since chart version 0.9.0 there seems to be an indentation issue when using value `ingress.traefikCRD.middlewares.chains.ingressRoute.before`, resulting in helm being unable to render the template with this error:

```
Error: YAML parse error on authelia/charts/authelia/templates/traefikCRD/middlewares.yaml: error converting YAML to JSON: yaml: line 15: did not find expected key
```

Using `after` instead of `before` works just fine

The following snippet in values

```yaml
        chains:
          auth:
            # nameOverride: authelia-auth-chain

            # List of Middlewares to apply before the forwardAuth Middleware in the authentication chain.
            before: 
            - name: before-header
              namespace: traefik
```

results in the following wrongly indented yaml

```yaml
# Source: authelia/charts/authelia/templates/traefikCRD/middlewares.yaml
# ...
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: chain-authelia
  labels:
    app.kubernetes.io/name: authelia
    app.kubernetes.io/instance: authelia
    app.kubernetes.io/version: 4.38.9
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: authelia-0.9.0
spec:
  chain:
    middlewares:
    - name: before-header
      namespace: traefik
      - name: headers-authelia
        namespace: auth
```

**Comment by james-d-elliott** [comment]
Figured it out, should be the following:

```yaml
ingress:
  enabled: true
  traefikCRD:
    enabled: true
    middlewares:
      chains:
        ingressRoute:
          before:
          - name: before-header
            namespace: traefik
```
