### ISSUE TITLE
User is able to access site, even with error: Access to 'https://domain.com/' is forbidden to user '<anonymous>'

### ISSUE THREAD

**Issue by usma0118** [authelia/chartrepo#251]
I am running authelia on kubernets.

Docker image: authelia/authelia:4.38.9

I am starting to face one strange issue. On some sites (configured via ingress) auth is skipped, and related site is served:

It's only happening on a few sites. ([log.txt](https://github.com/user-attachments/files/16440948/log.txt) attached) 

```
Ingress annotations:
    nginx.ingress.kubernetes.io/auth-method: GET
    nginx.ingress.kubernetes.io/auth-response-headers: Remote-User,Remote-Name,Remote-Groups,Remote-Email
    nginx.ingress.kubernetes.io/auth-signin: https://auth.domain.com?rm=$request_method
    nginx.ingress.kubernetes.io/auth-snippet: |
      proxy_set_header X-Forwarded-Method $request_method;
[log.txt](https://github.com/user-attachments/files/16440892/log.txt)

    nginx.ingress.kubernetes.io/auth-url: http://authelia.security.svc.cluster.local:9091/api/verify
```

config file is as follows:
```
session:
  name: "home"
  same_site: lax
  inactivity: 5m
  expiration: 1h
  remember_me: 1M
  cookies:
    - domain: ${SECRET_DOMAIN}
      name: '${SECRET_DOMAIN}_session'
      authelia_url: 'https://auth.${SECRET_DOMAIN}'
      default_redirection_url: 'https://www.${SECRET_DOMAIN}'
access_control:
  default_policy: deny
  networks:
    - name: home
      networks:
        - ${LOCAL_SUBNET_RANGE}
        - ${SECRET_DOMAIN_PUBLICIP}
    - name: vpn
      networks:
        - ${VPN_SUBNET_RANGE}
  rules:
    - domain:
        - "*.${SECRET_DOMAIN}"
        - "${SECRET_DOMAIN}"
      resources:
        - "^/api([/?].*)?$"
        - "^/identity.*$"
        - "^/triggers.*$"
        - "^/meshagents.*$"
        - "^/meshsettings.*$"
        - "^/agent.*$"
        - "^/control.*$"
        - "^/meshrelay.*$"
        - "^/wl.*$"
      policy: bypass
    - domain:
        - "*.${SECRET_DOMAIN}"
      networks:
        - home
        - vpn
      policy: one_factor
      subject:
        - ['group:Home']
        - ['group:admin']
    - domain:
        - "auth.${SECRET_DOMAIN}"
      policy: bypass
    - domain:
        - "movies.${SECRET_DOMAIN}"
        - "series.${SECRET_DOMAIN}"
        - "anime.${SECRET_DOMAIN}"
        - "metube.${SECRET_DOMAIN}"
        - "subtitles.${SECRET_DOMAIN}"
        - "indexers.${SECRET_DOMAIN}"
        - "prowlarr.${SECRET_DOMAIN}"
        - "whisparr.${SECRET_DOMAIN}"
        - "maintainerr.${SECRET_DOMAIN}"
      policy: one_factor
      networks:
        - home
      subject:
        - ['group:media_manager']
```
