### ISSUE TITLE
Upgrade from 4.38.16 to 4.38.17, SMTP authentication fails at startup.

### ISSUE THREAD

**Issue by mwinters-stuff** [authelia/chartrepo#275]
### Version

v4.38.17

### Deployment Method

Kubernetes

### Reverse Proxy

Traefik

### Reverse Proxy Version

Latest

### Description

Upgrading authelia from 4.38.16 to 4.38.17, the authentication to smtp fails at startup.

Rolling back to the prior version succeeds.

Upgrade/Downgrade is done via the authelia helm chart, by upgrading the image tag.

### Reproduction

Upgrade with config as shown below

### Expectations

Authelia should startup properly.

### Configuration (Authelia)

```yaml
---
# yaml-language-server: $schema=https://www.authelia.com/schemas/v4.38/json-schema/configuration.json
theme: 'light'
default_2fa_method: 'totp'
server:
  address: 'tcp://0.0.0.0:9091/'
  asset_path: ''
  headers:
    csp_template: ''
  buffers:
    read: 4096
    write: 4096
  timeouts:
    read: '6 seconds'
    write: '6 seconds'
    idle: '30 seconds'
  endpoints:
    enable_pprof: false
    enable_expvars: false
    authz:
      auth-request:
        implementation: 'AuthRequest'
      ext-authz:
        implementation: 'ExtAuthz'
      forward-auth:
        implementation: 'ForwardAuth'
log:
  level: 'info'
  format: 'text'
  file_path: ''
  keep_stdout: true
telemetry:
  metrics:
    enabled: false
identity_validation:
  elevated_session:
    code_lifespan: '5 minutes'
    elevation_lifespan: '10 minutes'
    characters: 8
    require_second_factor: false
    skip_second_factor: false
  reset_password:
    jwt_lifespan: '5 minutes'
    jwt_algorithm: 'HS256'
totp:
  disable: false
 ...
webauthn:
...
ntp:
  address: 'udp://time.cloudflare.com:123'
  version: 4
  max_desync: '3 seconds'
  disable_startup_check: false
  disable_failure: false
authentication_backend:
  password_reset:
    disable: false
    custom_url: ''
  ldap:
    implementation: 'custom'
...
password_policy:
  standard:
    enabled: false
    min_length: 8
    max_length: 0
    require_uppercase: false
    require_lowercase: false
    require_number: false
    require_special: false
  zxcvbn:
    enabled: false
    min_score: 0
session:
  name: 'authelia_session'
  same_site: 'lax'
  inactivity: '5 minutes'
  expiration: '1 hour'
  remember_me: '1 month'
  cookies:
    - domain: 'somplace.com'
      authelia_url: 'https://auth.somplace.com'
  redis:
...
regulation:
  max_retries: 3
  find_time: '2 minutes'
  ban_time: '7 weeks'
storage:
  postgres:
...
notifier:
  disable_startup_check: false
  smtp:
    address: 'submission://internal.somplace.com:587/'
    timeout: '5 seconds'
    username: 'authelia'
    sender: 'Authelia <authelia@internal.somplace.com>'
    identifier: 'authelia'
    subject: '[Authelia] {title}'
    startup_check_address: 'authelia@internal.somplace.com'
    disable_html_emails: false
    disable_require_tls: false
    disable_starttls: false
    tls:
      server_name: ''
      skip_verify: false
      minimum_version: 'TLS1.2'
      maximum_version: 'TLS1.3'
...```

```
authelia password secret
```
apiVersion: v1
kind: Secret
metadata:
  name: authelia
  namespace: web-auth
  uid: 7f3483ba-add6-4f0f-867f-324b1647d2ae
  resourceVersion: '41198365'
  creationTimestamp: '2024-06-26T04:44:05Z'
  labels:
    kustomize.toolkit.fluxcd.io/name: apps
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  selfLink: /api/v1/namespaces/web-auth/secrets/authelia
data:
  notifier.smtp.password.txt: YXV0aGVsaWE=
type: Opaque

```

### Build Information

```shell
Last Tag: v4.38.17
State: tagged clean
Branch: v4.38.17
Commit: 592ab519b4167dfe4462ee0a613d38d3e4b8efa0
Build Number: 35061
Build OS: linux
Build Arch: amd64
Build Compiler: gc
Build Date: Thu, 31 Oct 2024 09:37:31 +1100
Extra: 

Go:
    Version: go1.23.2
    Module Path: github.com/authelia/authelia/v4
    Executable Path: github.com/authelia/authelia/v4/cmd/authelia
```

### Logs (Authelia)

```shell
Logs from 4.38.17
time="2024-11-07T15:19:50+13:00" level=info msg="Authelia v4.38.17 is starting"
time="2024-11-07T15:19:50+13:00" level=info msg="Log severity set to info"
time="2024-11-07T15:19:50+13:00" level=info msg="Storage schema is being checked for updates"
time="2024-11-07T15:19:50+13:00" level=info msg="Storage schema is already up to date"
time="2024-11-07T15:19:51+13:00" level=error msg="Error occurred running a startup check" error="failed to dial connection: SMTP AUTH failed: 535 5.7.8 Error: authentication failed: authentication failure" provider=notification
time="2024-11-07T15:19:51+13:00" level=fatal msg="One or more providers had fatal failures performing startup checks, for more detail check the error level logs" providers="[notification]" stack="github.com/authelia/authelia/v4/internal/commands/root.go:150 doStartupChecks\ngithub.com/authelia/authelia/v4/internal/commands/root.go:88 (*CmdCtx).RootRunE\ngithub.com/spf13/cobra@v1.8.1/command.go:985 (*Command).execute\ngithub.com/spf13/cobra@v1.8.1/command.go:1117 (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.8.1/command.go:1041 (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10 main\ninternal/runtime/atomic/types.go:194 (*Uint32).Load\nruntime/asm_amd64.s:1700 goexit"


Logs from prior version
time="2024-11-07T12:59:36+13:00" level=info msg="Authelia v4.38.16 is starting"
time="2024-11-07T12:59:36+13:00" level=info msg="Log severity set to info"
time="2024-11-07T12:59:36+13:00" level=info msg="Storage schema is being checked for updates"
time="2024-11-07T12:59:36+13:00" level=info msg="Storage schema is already up to date"
time="2024-11-07T12:59:37+13:00" level=info msg="Startup complete"
time="2024-11-07T12:59:37+13:00" level=info msg="Listening for non-TLS connections on '[::]:9091' path '/'" server=main service=server
```

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] This is a bug report and not a support request

- [X] I have read the security policy and this bug report is not a security issue or security related issue

- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration

- [X] I have either included the complete debug / trace logs or the output of the build-info command if the logs are not relevant

- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide

- [X] I have checked for related proxy or application logs and included them if available

- [X] I have checked for related issues and checked the documentation
