### ISSUE TITLE
any reason why existing sessions die when rolling out new config?

### ISSUE THREAD

**Issue by torsteinelv** [authelia/chartrepo#279]
If I update any paramenters in authelia all sessions are reset and all users needs to login again? 

Is this by design or have i missconfigured something?

**Comment by Crowley723** [comment]
This is likely due to the lack of Redis. By default, authelia isn't fully stateless. If you want sessions to persist across restarts, you should configure redis.

**Comment by torsteinelv** [comment]
Thanks for your reply. I have configured redis. Is there any way tips on how to troubleshoot this?

**Comment by Crowley723** [comment]
If you are familiar with redis-cli, you can view keys in Redis. I would suggest making sure a new session is stored in Redis when a new session is created and that they are still there when Authelia restarts.

**Comment by torsteinelv** [comment]
Ok. Thanks alot. I will figure it out from here.

**Comment by torsteinelv** [comment]
Hello, 

I have now tested and I can see all 3 sessions in the redis-cli so I guess this is not the problem then?

Im sharing my config just in case someone understand why:
```
apiVersion:` argoproj.io/v1alpha1
kind: Application
metadata:
  name: authelia
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.authelia.com
    chart: authelia
    targetRevision: 0.9.14
    helm:
      values: |
        session:
          expiration: '24 hour'
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
            kubernetes.io/ingress.class: "nginx"
            external-dns.alpha.kubernetes.io/hostname: "auth.domain.com"
            external-dns.alpha.kubernetes.io/target: "nginx.domain.com"
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
          className: "nginx"
          certManager: true
          rewriteTarget: false
          rulesOverride:
            - host: 'auth.domain.com'
              path: '/'
          tls:
            enabled: true
            secret: 'authelia-tls'
            
        configMap:
          theme: dark
          
          duo_api:
            enabled: true
            hostname: 'duohost'
            integration_key: 'duokey'
            enable_self_enrollment: false
            secret:
              disabled: false
              secret_name: authelia-secrets
              path: "duo_secret_key"

                
          notifier:
            smtp:
              enabled: true
              address: 'submission://192.168.1.10:25'
              sender: authelia@domain.com # Sender email address
              identifier: localhost      # Identifier for email headers (typically used for testing)
              subject: "[Authelia] {title}" # Email subject template
              startup_check_address: mail@domain.com # Address for startup checks (if applicable)
              disable_require_tls: true  # Disables the requirement for TLS
              disable_html_emails: true  # Disables HTML emails
              username: ''
              password:
                disabled: true
              tls:
                skip_verify: true        # Skips TLS certificate verification
                minimum_version: TLS1.2  # Minimum TLS version required
          authentication_backend:
            ldap:
              enabled: true
              implementation: 'lldap'
              address: 'ldap://lldap:3890'
              base_dn: 'dc=domain,dc=com'
              user: 'uid=readonly,ou=people,dc=domain,dc=com'
              additional_users_dn: 'OU=people'
              password:
                value: 'readonly'
          storage:
            encryption_key:
              value: 'examplekey'
            postgres:
              enabled: true
              deploy: true
              address: 'tcp://authelia-postgresql:5432'
              password:
                value: 'authelia'
          session:
            redis:
              enabled: true
              deploy: true
              host: 'authelia-redis-master'
            cookies:
              - domain: "domain.com"
                authelia_url: 'https://auth.domain.com'
                name: 'authelia_session'
                same_site: 'lax'
                inactivity: '1d'
                expiration: '1d'
                remember_me: '1d'
          access_control:
            default_policy: deny
            rules:
              - domain: "test.domain.com"
                policy: bypass
                resources:
                - '^/v2([/?].*)?$'
              - domain: "*.domain.com"
                policy: two_factor
                subject:
                  - "group:lldap_admin"
        postgresql:
          primary:
            persistence:
              enabled: true

        redis:
          architecture: standalone
          auth:
            enabled: false
            
        secret:
          disabled: false
          existingSecret: ''
          mountPath: /secrets
          additionalSecrets:
            authelia-secrets:
              items:
                - key: duo_integration_key
                  path: duo_integration_key
                - key: duo_secret_key
                  path: duo_secret_key       
  destination:
    server: https://kubernetes.default.svc
    namespace: authelia
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
```

**Comment by james-d-elliott** [comment]
Looks like you've not configured any persistence settings for redis.

**Comment by torsteinelv** [comment]
persistent storage fixed the problem. thanks again.

**Comment by mathieures** [comment]
If it can help someone, this is what I added to tto the values is enough to make sessions persistent across restarts of the Authelia pod (it seems they don’t need to "be manually copied from here to the session.redis section" as the comment in the default `values.yaml` file suggests):
```yml
redis:
  master:
    persistence:
      enabled: true
```
