### ISSUE TITLE
0.9.17 -> 0.10.3 storage issue: unable to open database

### ISSUE THREAD

**Issue by jacobw** [authelia/chartrepo#287]
After upgrading to 0.10.3 I get the following errors:

```
time="2025-03-19T06:40:07Z" level=info msg="Authelia v4.39.1 is starting"
time="2025-03-19T06:40:07Z" level=info msg="Log severity set to info"
time="2025-03-19T06:40:16Z" level=error msg="Error occurred running a startup check" error="error pinging database: unable to open database file: no such file or directory" provider=storage
time="2025-03-19T06:40:17Z" level=fatal msg="One or more providers had fatal failures performing startup checks, for more details check the error level logs" providers="[storage]" stack="github.com/authelia/authelia/v4/internal/commands/root.go:94 (*CmdCtx).RootRunE\ngithub.com/spf13/cobra@v1.9.1/command.go:1015                (*Command).execute\ngithub.com/spf13/cobra@v1.9.1/command.go:1148                (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.9.1/command.go:1071                 (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10      main\ninternal/runtime/atomic/types.go:194                         (*Uint32).Load\nruntime/asm_amd64.s:1700    
```

I've tried to read the source too see what's changed but can't fin anything obvious.

I have a pretty basic config for testing.

I've downgraded and upgraded a couple of times and have done fresh installs but it seems to happen every time. I assume this error means it can't open the sqlite db, but I assume it should create it if its missing too?

values:
```
  values:
    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/enable-global-auth: "false"
    pod:
      kind: Deployment
    configMap:
      notifier:
        disable_startup_check: true
        filesystem:
          enabled: true
      access_control:
        default_policy: deny
        rules:
        - domain: <redacted>
          policy: one_factor
      storage:
        local:
          enabled: true
      authentication_backend:
        ldap:
          enabled: true
          implementation: lldap
          address: ldap://lldap-ldap.lldap.svc.cluster.local:3890
          base_dn: <redacted>
          user: uid=<redacted>
          additional_users_dn: ''
      session:
        cookies:
          -
            subdomain: auth
            domain: <redacted>
```
