### ISSUE TITLE
TraefikCRD block configuration

### ISSUE THREAD

**Issue by flixman** [authelia/chartrepo#289]
Hi there! I am trying to set up a fresh installation of authelia using the helm chart. I am using a default TLS certificate in traefik, so that I only want it to route the connections to the correct service. For that, I am using this block

```
ingress:
  enabled: true
  
  traefikCRD:
    enabled: true
    entryPoints:
      - websecure
    matchOverride: Host(`auth.{{ domain }}`) && PathPrefix(`/`)
```
and is giving me this error back:
```
Error: 1 error occurred:
     * IngressRoute.traefik.io "authelia" is invalid: spec.routes: Required value
```
What am I doing wrong?
