### ISSUE TITLE
Headers CSP Template

### ISSUE THREAD

**Issue by whezzel** [authelia/chartrepo#292]
I'm not sure exactly what info y'all need for an issue report but here are some specs I think are relevant. Let me know if you need anything else.

k8s version: 1.32.3
helm version: v3.17.2
chart version: 0.10.4

## Issue

I am unable to set a csp template using the option in the values. No matter what value I set for the csp_template value, it fails to parse. The only way I was able to get it to work was by setting the csp_template as an env variable with the name `AUTHELIA_SERVER_HEADERS_CSP_TEMPLATE`

I tried several variations of defining it in my values. Even the default value (below) results in a parsing error and the rest of the config fails to load.

```
server:
 headers:
   csp_template: default-src 'self'; frame-src 'none'; object-src 'none'; style-src 'self' 'nonce-${NONCE}'; frame-ancestors 'none'; base-uri 'self'
```
The below log indicates multiple configuration options aren't set, but that's only because of the parsing issue with the csp_template. If I remove the csp_template, the configmap is generated and authelia works as expected.

```
time="2025-04-14T17:34:23-05:00" level=error msg="Configuration: failed to load configuration from file path(/configuration.yaml) source: yaml: line 8: did not find expected key"
time="2025-04-14T17:34:23-05:00" level=error msg="Configuration: failed to load configuration from file path(/configuration.yaml) source: yaml: line 8: did not find expected key"
time="2025-04-14T17:34:23-05:00" level=error msg="Configuration: authentication_backend: ldap: option 'address' is required"
time="2025-04-14T17:34:23-05:00" level=error msg="Configuration: authentication_backend: ldap: option 'user' is required"
time="2025-04-14T17:34:23-05:00" level=error msg="Configuration: authentication_backend: ldap: option 'users_filter' is required"
time="2025-04-14T17:34:23-05:00" level=error msg="Configuration: authentication_backend: ldap: option 'groups_filter' is required"
time="2025-04-14T17:34:23-05:00" level=error msg="Configuration: access_control: 'default_policy' option 'deny' is invalid: when no rules are specified it must be 'two_factor' or 'one_factor'"
time="2025-04-14T17:34:23-05:00" level=error msg="Configuration: session: redis: option 'host' is required"
time="2025-04-14T17:34:23-05:00" level=error msg="Configuration: session: option 'cookies' is required"
time="2025-04-14T17:34:23-05:00" level=error msg="Configuration: storage: postgres: option 'address' is required"
time="2025-04-14T17:34:23-05:00" level=error msg="Configuration: storage: postgres: option 'username' is required"
time="2025-04-14T17:34:23-05:00" level=error msg="Configuration: storage: postgres: option 'database' is required"
time="2025-04-14T17:34:23-05:00" level=error msg="Configuration: notifier: smtp: option 'address' is required"
time="2025-04-14T17:34:23-05:00" level=error msg="Configuration: notifier: smtp: option 'sender' is required"
time="2025-04-14T17:34:23-05:00" level=error msg="Configuration: identity_providers: oidc: option `jwks` is required"
time="2025-04-14T17:34:23-05:00" level=error msg="Configuration: identity_providers: oidc: option 'clients' must have one or more clients configured"
time="2025-04-14T17:34:23-05:00" level=fatal msg="Can't continue due to the errors loading the configuration" stack="github.com/authelia/authelia/v4/internal/commands/context.go:157 NewRootCmd.(*CmdCtx).ChainRunE.func1\ngithub.com/spf13/cobra@v1.9.1/command.go:1000                    (*Command).execute\ngithub.com/spf13/cobra@v1.9.1/command.go:1148                    (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.9.1/command.go:1071                    (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10          main\ninternal/runtime/atomic/types.go:194                             (*Uint32).Load\nruntime/asm_amd64.s:1700                                         goexit"
```

Even a simplified csp template (below) causes a parsing error

```
server:
 headers:
   csp_template: default-src 'self'
```

**Comment by james-d-elliott** [comment]
Show the template input values at the very least.

**Comment by whezzel** [comment]
I'm sorry. I don't know what you mean. I included two (2) variations of the csp template I tried using in my values file.

The first `default-src 'self'; frame-src 'none'; object-src 'none'; style-src 'self' 'nonce-${NONCE}'; frame-ancestors 'none'; base-uri 'self'` being the documented default template (https://www.authelia.com/configuration/miscellaneous/server/#csp_template), and the second being a much more simplified template `default-src 'self'`.

Here is the actual template I'm trying to implement. `default-src 'self'; frame-src 'none'; object-src 'none'; style-src 'self' 'nonce-${NONCE}'; frame-ancestors 'self' homeassistant.example.com; base-uri 'self'`.

If this isn't what you're asking for, please let me know.

**Comment by whezzel** [comment]
Here is the entirety of the values I pass to helm

```
ingress:
  enabled: true
  rulesOverride:
    - host: authelia.example.com
      path: /
  className: 'nginx'
  tls:
    enabled: true
    secret: ''
pod:
  kind: 'Deployment'
  replicas: 3
  selectors:
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - authelia
            - key: app.kubernetes.io/instance
              operator: In
              values:
              - authelia
          topologyKey: "kubernetes.io/hostname"
  env:
    - name: 'TZ'
      value: 'America/Chicago'
    - name: AUTHELIA_SERVER_HEADERS_CSP_TEMPLATE
      value: "default-src 'self'; frame-src 'none'; object-src 'none'; style-src 'self' 'nonce-${NONCE}'; frame-ancestors 'self' homeassistant.example.com; base-uri 'self'"
configMap:
  disabled: false
  filters:
    disabled: false
  server:
    #headers:
    #  csp_template:
    endpoints:
      authz:
        auth-request:
          implementation: 'AuthRequest'
          authn_strategies:
          - name: 'HeaderAuthRequestProxyAuthorization'
            schemes:
            - 'Basic'
          - name: 'CookieSession'
        ext-authz:
          implementation: 'ExtAuthz'
          authn_strategies:
          - name: 'HeaderProxyAuthorization'
            schemes:
            - 'Basic'
          - name: 'CookieSession'
        forward-auth:
          implementation: 'ForwardAuth'
          authn_strategies:
          - name: 'HeaderProxyAuthorization'
            schemes:
            - 'Basic'
          - name: 'CookieSession'
  log:
    level: 'debug' # info, debug, trace
  telemetry:
    metrics:
      enabled: false
      serviceMonitor:
        enabled: false
  default_2fa_method: 'webauthn'
  theme: 'dark'
  definitions:
    network:
      k8s:
        - '10.244.0.0/16'
      LAN:
        - '10.0.0.0/16'
  identity_validation:
    reset_password:
      jwt_lifespan: '5 minutes'
      jwt_algorithm: 'HS256'
      secret:
        disabled: false
        secret_name: ~
        value: 'none-ya-business'
        path: 'identity_validation.reset_password.jwt.hmac.key'
    elevated_session:
      code_lifespan: '5 minutes'
      elevation_lifespan: '10 minutes'
      characters: 10
      require_second_factor: true
      skip_second_factor: false
  totp:
    disable: false
    issuer: 'Authelia'
    skew: 1
    secret_size: 32
    algorithm: 'SHA1'
    digits: 6
    period: 30
    allowed_algorithms:
      - 'SHA1'
    allowed_digits:
      - 6
    allowed_periods:
      - 30
  webauthn:
    disable: false
    timeout: '60 seconds'
    display_name: 'Authelia'
    attestation_conveyance_preference: 'indirect'
    filtering:
      permitted_aaguids: []
      prohibited_aaguids: []
      prohibit_backup_eligibility: false
    selection_criteria:
      attachment: ''
      discoverability: 'preferred'
      user_verification: 'preferred'
    metadata:
      enabled: false
      validate_trust_anchor: true
      validate_entry: true
      validate_entry_permit_zero_aaguid: false
      validate_status: true
      validate_status_permitted: []
      validate_status_prohibited: []
  ntp:
    address: 'udp://1.1.1.1:123'
    version: 3
    max_desync: '3 seconds'
    disable_startup_check: false
    disable_failure: false
  authentication_backend:
    password_reset:
      disable: false
      custom_url: ''
    password_change:
      disable: false
    refresh_interval: '5 minutes'
    ldap:
      enabled: true
      implementation: 'custom'
      address: 'ldap://openldap.auth:389'
      timeout: '5 seconds'
      start_tls: false
      tls:
        server_name: ''
        skip_verify: false
        minimum_version: 'TLS1.2'
        maximum_version: 'TLS1.3'
      pooling:
        enable: false
        count: 5
        retries: 2
        timeout: '10 seconds'
      base_dn: 'dc=example,dc=com'
      additional_users_dn: 'ou=users'
      users_filter: '(&(|({username_attribute}={input})({mail_attribute}={input}))(objectClass=person))'
      additional_groups_dn: 'ou=groups'
      groups_filter: '(&(member={dn})(objectclass=groupOfNames))'
      permit_referrals: true
      permit_unauthenticated_bind: false
      permit_feature_detection_failure: false
      user: 'cn=bind_authelia,ou=services,dc=example,dc=com'
      password:
        disabled: false
        secret_name: ~
        value: 'none-ya-business'
        path: 'authentication.ldap.password.txt'
      attributes:
        distinguished_name: 'distinguishedName'
        username: 'uid'
        display_name: 'displayName'
        family_name: ''
        given_name: ''
        middle_name: ''
        nickname: ''
        gender: ''
        birthdate: ''
        website: ''
        profile: ''
        picture: ''
        zoneinfo: ''
        locale: ''
        phone_number: ''
        phone_extension: ''
        street_address: ''
        locality: ''
        region: ''
        postal_code: ''
        country: ''
        mail: 'mail'
        member_of: 'memberOf'
        group_name: 'cn'
        extra: {}
  password_policy:
    standard:
      enabled: false
      min_length: 8
      max_length: 0
      require_uppercase: false
      require_lowercase: false
      require_number: false
      require_special: false
    zxcvbn:
      enabled: false
      min_score: 0
  access_control:
    secret:
      enabled: false
      key: 'configuration.acl.yaml'
      existingSecret: ''
    default_policy: 'deny'
    rules:
      - domain: "*.example.com"
        subject:
          - "group:admins"
        policy: two_factor
  session:
    name: 'authelia_session'
    same_site: 'lax'
    expiration: '1 hour'
    inactivity: '5 minutes'
    remember_me: '1 month'
    encryption_key:
      disabled: false
      secret_name: ~
      value: 'none-ya-business'
      path: 'session.encryption.key'
    cookies:
      - name: 'authelia_session'
        domain: 'example.com'
        authelia_url: 'https://authelia.example.com'
        inactivity: '5 minutes'
        expiration: '1 hour'
        remember_me: '2 month'
    redis:
      enabled: true
      deploy: false
      enabledSecret: false
      host: 'authelia-redis.auth'
      port: 6379
      username: 'default'
      password:
        disabled: false
        secret_name: ~
        value: 'none-ya-business'
        path: 'session.redis.password.txt'
      database_index: 0
      maximum_active_connections: 8
      minimum_idle_connections: 0
      tls:
        enabled: false
        server_name: ''
        skip_verify: false
        minimum_version: 'TLS1.2'
        maximum_version: 'TLS1.3'
      high_availability:
        enabled: false
        enabledSecret: false
        sentinel_name: 'mysentinel'
        username: ''
        password:
          disabled: false
          secret_name: ~
          value: ''
          path: 'session.redis.sentinel.password.txt'
        nodes: []
        route_by_latency: false
        route_randomly: false
    modes:
      - 'user'
    max_retries: 3
    find_time: '2 minutes'
    ban_time: '5 minutes'
  storage:
    encryption_key:
      disabled: false
      secret_name: ~
      value: 'none-ya-business'
      path: 'storage.encryption.key'
    postgres:
      enabled: true
      deploy: false
      address: 'tcp://authelia-postgres-rw.database:5432'
      timeout: '5 seconds'
      database: 'authelia'
      schema: 'public'
      username: 'authelia'
      password:
        disabled: false
        secret_name: ~
        value: 'none-ya-business'
        path: 'storage.postgres.password.txt'
      tls:
        enabled: false
        server_name: ''
        skip_verify: false
        minimum_version: 'TLS1.2'
        maximum_version: 'TLS1.3'
  notifier:
    disable_startup_check: false
    smtp:
      enabled: true
      enabledSecret: false
      address: 'submissions://docker-mailserver.email:465'
      timeout: '5 seconds'
      sender: 'Authelia <hello@example.com>'
      identifier: 'example.com'
      subject: '[Authelia] {title}'
      startup_check_address: 'test@authelia.com'
      disable_html_emails: false
      disable_require_tls: false
      disable_starttls: false
      username: 'hello@example.com'
      password:
        disabled: false
        secret_name: ~
        value: 'none-ya-business'
        path: 'notifier.smtp.password.txt'
      tls:
        server_name: 'authelia.example.com'
        skip_verify: false
        minimum_version: 'TLS1.2'
        maximum_version: 'TLS1.3'
  identity_providers:
    oidc:
      enabled: true
      issuer_private_keys:
        - key_id: "default"
          algorith: RS256
          key:
            value: |
              none-ya-business
      hmac_secret:
        disabled: false
        secret_name: ~
        value: 'none-ya-business'
        path: 'identity_providers.oidc.hmac.key'
      lifespans:
        access_token: '1 hour'
        authorize_code: '1 minute'
        id_token: '1 hour'
        refresh_token: '1 hour and 30 minutes'
      claims_policies: {}
      scopes: {}
      enforce_pkce: 'public_clients_only'
      enable_pkce_plain_challenge: false
      minimum_parameter_entropy: 8
      enable_client_debug_messages: false
      pushed_authorizations:
        enforce: false
        context_lifespan: '5 minutes'
      authorization_policies: {}
      jwks:
        - key_id: 'default'
          algorithm: 'RS256'
          use: sig
          key:
            value: |
              none-ya-business
      cors:
        endpoints: []
        allowed_origins: []
        allowed_origins_from_client_redirect_uris: false
      clients:
        # k run --image authelia/authelia:latest authelia -it --rm --command -- authelia crypto hash generate pbkdf2 --variant sha512 --random --random.length 72 --random.charset rfc3986
        - client_id: 'dms'
          client_name: 'dms'
          client_secret: none-ya-business'
          public: false
          authorization_policy: 'two_factor'
          consent_mode: 'implicit'
          require_pkce: true
          pkce_challenge_method: 'S256'
          redirect_uris:
            - 'https://mail.ecample.com/oauth2/callback'
          scopes:
            - 'openid'
            - 'profile'
            - 'groups'
            - 'email'
          userinfo_signed_response_alg: 'none'
          token_endpoint_auth_method: 'client_secret_basic'
```
