### ISSUE TITLE
Automatically recreate pods on config change

### ISSUE THREAD

**Issue by gtrubach** [authelia/chartrepo#42]
Hello,

Right now Authelia does not have hot reload. With Helm it's possible to automatically rollout the pods in case configuration changed based on the file checksum.

Is it possible to add to this chart the technique described here - https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments? Basically to make pods react to config changes it's required to add something like this:
```yaml
kind: Deployment
spec:
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configMap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        # other files which requires pod restart
```

Since the checksum will change on files change, annotation of deployment will change and pods will be recreated.
