### ISSUE TITLE
Question: Why are there two different Traefik Middleware chains?

### ISSUE THREAD

**Issue by trallnag** [authelia/chartrepo#87]
Looking at the generated template I find the following two middlewares. Is there a specific reason for having two?

```yaml
---
# Source: authelia/templates/traefikCRD/middlewares.yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: chain-authelia-auth
  labels: 
    app.kubernetes.io/name: authelia
    app.kubernetes.io/instance: authelia
    app.kubernetes.io/version: 4.29.4
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: authelia-0.4.19
spec:
  chain:
    middlewares:
      - name: forwardauth-authelia
        namespace: default
---
# Source: authelia/templates/traefikCRD/middlewares.yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: chain-authelia
  labels:
    app.kubernetes.io/name: authelia
    app.kubernetes.io/instance: authelia
    app.kubernetes.io/version: 4.29.4
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: authelia-0.4.19
spec:
  chain:
    middlewares:
      - name: headers-authelia
        namespace: default
```
Relevant part of config:

```yaml
ingress:
  enabled: true

  traefikCRD:
    enabled: true

    entryPoints:
      - websecure

    middlewares:
      auth:
        authResponseHeaders:
        - Remote-User
        - Remote-Name
        - Remote-Email
        - Remote-Groups

      chains:
        auth:
          before: []

          after: []

        ingressRoute:

          before: []

          after: []
  
```
